site_name: EABIAS
site_url: https://eabias.github.io/

theme:
  name: material
  logo: images/EABIAS_Logo_W.png
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode



  features:
  #  - navigation.instant
  #  - navigation.instant.progress
  #  - navigation.instant.preview
  #  - navigation.instant.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotation
    - content.code.copy
    
plugins:
  - search
  #- tags
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "EABIAS"
        - locale: zh-TW
          name: Chinese
          build: true
          site_name: "EABIAS"
        - locale: ja
          name: Japanese
          build: true
          site_name: "EABIAS"


nav:
  - Home: index.md
  - About EABIAS: about.md
  - Activities: activities.md
  - Resources: resources.md
  - Microscopy DB: microscopy_db.md
#  - Tags: tags.md

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Chinese
      link: /zh-TW/
      lang: zh-TW
    - name: Japanese
      link: /ja/
      lang: ja

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
# ------------------------------------
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

#markdown_extensions:
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.superfences
